name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Check out sources'
      uses: actions/checkout@v2
    - name: 'Set up Java'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Build with Bach'
      run: jshell https://sormuras.de/bach@11.6/build
